# Generated by Django 2.1.5 on 2019-02-03 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190203_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='choices',
        ),
        migrations.AddField(
            model_name='choice',
            name='stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Stage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='stage_a',
            field=models.ManyToManyField(related_name='_stage_stage_a_+', to='core.Stage'),
        ),
        migrations.AddField(
            model_name='stage',
            name='stage_b',
            field=models.ManyToManyField(related_name='_stage_stage_b_+', to='core.Stage'),
        ),
    ]
