# Generated by Django 2.1.5 on 2019-02-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190203_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_b',
            field=models.BooleanField(default=False),
        ),
    ]
