# Generated by Django 2.1.5 on 2019-02-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190203_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='stage_a',
            field=models.ManyToManyField(blank=True, related_name='_stage_stage_a_+', to='core.Stage'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_b',
            field=models.ManyToManyField(blank=True, related_name='_stage_stage_b_+', to='core.Stage'),
        ),
    ]
