# Generated by Django 2.1.5 on 2019-02-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190203_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='end_stage',
            field=models.BooleanField(default=False),
        ),
    ]
