# Generated by Django 2.1.5 on 2019-02-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_stage_end_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='root',
            field=models.BooleanField(default=False),
        ),
    ]
