# Generated by Django 2.1.5 on 2019-02-03 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_stage_root'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='stage',
        ),
        migrations.AddField(
            model_name='game',
            name='stage',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Stage'),
            preserve_default=False,
        ),
    ]
