# Generated by Django 2.1.5 on 2019-02-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190203_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='game_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
