# Generated by Django 2.1.5 on 2019-02-03 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190203_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='stage_a',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='stage_b',
        ),
        migrations.AddField(
            model_name='stage',
            name='a_stage',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stage_a', to='core.Stage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='b_stage',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stage_b', to='core.Stage'),
            preserve_default=False,
        ),
    ]
